# version key is DEPRECATED
# v2 and v3 features now combined in compose CLI

services:
  node:
    build:
      dockerfile: 5.Dockerfile
      context: .
      target: dev
    volumes:
      - .:/app:delegated
    ports:
      - "3000:3000"

  db:
    image: postgres
